### ISSUE TITLE
No such var: keypin/lookup-property

### ISSUE THREAD

**Issue by ghost** [kumarshantanu/keypin#2]
I am getting the following error:
``` clojure
#error {
 :cause No such var: keypin/lookup-property
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.RuntimeException: No such var: keypin/lookup-property, compiling:(com/../core.clj:19:1)
   :at [clojure.lang.Compiler analyze Compiler.java 6688]}
  {:type java.lang.RuntimeException
   :message No such var: keypin/lookup-property
   :at [clojure.lang.Util runtimeException Util.java 221]}]
 :trace
 [[clojure.lang.Util runtimeException Util.java 221]
```
Found that `lookup-property` has been removed but it's still present in the documentation. Property lookup works fine without this method.

**Comment by kumarshantanu** [comment]
Thanks for reporting this! I will fix the doc to reflect the change. And yes, config key lookup should work fine without mentioning lookup fn because it defaults to looking up the key in the config map.
